/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.uas.pbo.gui;

import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class FrameInternalPemilik extends javax.swing.JInternalFrame {

    static ArrayList list_beli;
    static ArrayList list_jual;

    public FrameInternalPemilik() {
        initComponents();
    }

    public static void isiLaporanPembelian(JTextField text_id, JTextField text_nama, JTextField text_umur,
            JTextField text_harga, JTextField text_tanggal_beli) {
        DefaultTableModel data_beli = (DefaultTableModel) tabel_beli.getModel();
        list_beli = new ArrayList<>();
        tabel_beli.setAutoCreateColumnsFromModel(true);
        list_beli.add(text_id.getText());
        list_beli.add(text_nama.getText());
        list_beli.add(text_umur.getText());
        list_beli.add(text_harga.getText());
        list_beli.add(text_tanggal_beli.getText());
        data_beli.addRow(list_beli.toArray());
    }

    public static void isiLaporanPenjualan(JTextField text_id2, JTextField text_nama2, JTextField text_harga_beli2,
            JTextField text_tanggal_beli2, JTextField text_harga_jual2, JTextField text_tanggal_jual2,
            int total_untung) {
        if (tabel_beli.getRowCount() > 0) {
            DefaultTableModel data_jual = (DefaultTableModel) tabel_jual.getModel();
            tabel_jual.setAutoCreateColumnsFromModel(true);

            DefaultTableModel data_beli = (DefaultTableModel) tabel_beli.getModel();
            for (int i = 0; i < tabel_beli.getRowCount(); i++) {
                if (text_id2.getText().equals(tabel_beli.getValueAt(i, 0).toString())) {
                    list_jual = new ArrayList<>();
                    list_jual.add(text_nama2.getText());
                    list_jual.add(text_harga_beli2.getText());
                    list_jual.add(text_tanggal_beli2.getText());
                    list_jual.add(text_harga_jual2.getText());
                    list_jual.add(text_tanggal_jual2.getText());
                    data_beli.removeRow(i);
                    list_beli.remove(i);
                    int untung = Integer.parseInt(text_harga_jual2.getText()) - Integer.parseInt(text_harga_beli2.getText());
                    list_jual.add(untung);
                    data_jual.addRow(list_jual.toArray());
                    text_total_untung.setText("" + total_untung);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_tutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_beli = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_jual = new javax.swing.JTable();
        label_hewan_dibeli = new javax.swing.JLabel();
        label_hewan_dijual = new javax.swing.JLabel();
        label_total_untung = new javax.swing.JLabel();
        text_total_untung = new javax.swing.JTextField();

        button_tutup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_tutup.setText("Tutup");
        button_tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tutupActionPerformed(evt);
            }
        });

        tabel_beli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Hewan", "Nama Hewan", "Umur Hewan", "Harga Beli", "Tanggal Beli"
            }
        ));
        jScrollPane1.setViewportView(tabel_beli);

        tabel_jual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Hewan", "Harga Beli", "Tanggal Beli", "Harga Jual", "Tanggal Jual", "Keuntungan"
            }
        ));
        jScrollPane2.setViewportView(tabel_jual);

        label_hewan_dibeli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_hewan_dibeli.setText("                                  Laporan Pembelian");

        label_hewan_dijual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_hewan_dijual.setText("                                  Laporan Penjualan");

        label_total_untung.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        label_total_untung.setText("Total keuntungan : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                            .addComponent(label_hewan_dibeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                            .addComponent(label_hewan_dijual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_total_untung)
                        .addGap(14, 14, 14)
                        .addComponent(text_total_untung, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_hewan_dibeli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_hewan_dijual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_tutup, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(text_total_untung)
                    .addComponent(label_total_untung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tutupActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_button_tutupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_tutup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_hewan_dibeli;
    private javax.swing.JLabel label_hewan_dijual;
    private javax.swing.JLabel label_total_untung;
    public static javax.swing.JTable tabel_beli;
    public static javax.swing.JTable tabel_jual;
    private static javax.swing.JTextField text_total_untung;
    // End of variables declaration//GEN-END:variables
}
